### ISSUE TITLE
配置后不能用，返回400

### ISSUE THREAD

**Issue by guoyang1982** [tg123/websockify-nginx-module#13]
location /websockify {
            websockify_pass 10.58.93.148:5901;
        }
websocket：
        socket = new WebSocket("ws://10.127.96.195:80/websockify");
浏览器：
http://10.127.96.195/websockify
访问access.log里都是400

**Comment by guoyang1982** [comment]
这个是我的错误日志：
2018/08/01 18:49:05 [info] 8966#0: *10 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while reading upstream, client: 10.58.93.148, server: localhost, request: "GET /websockify HTTP/1.1", upstream: "websockify://10.58.93.148:5901", host: "10.127.96.195"

**Comment by tg123** [comment]
hi

ws 不能直接通过 http 访问
会返回400
你可以通过 https://www.websocket.org/echo.html 
输入 ws://.... 来做 echo test
