### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by chenyh** [tg123/websockify-nginx-module#15]
static ngx_int_t ngx_http_websockify_handler(ngx_http_request_t *r)

在这个函数里面。许多返回都不考虑ngx_pcalloc分配内存的释放？

**Comment by tg123** [comment]
那个内存池托管给 ngx 管理
在连接关闭时候ngx 会清理
没有释放一般是链接生命期内用到的

如果有具体代码可以指出一起讨论下
