### ISSUE TITLE
通过websockify-nginx能不能实现二次转发

### ISSUE THREAD

**Issue by JackZhai2018** [tg123/websockify-nginx-module#21]
|----------Internet-------------------|------------------intranet1-----------------------|--------------intranet2--------------|
                   1                                                                       2                                                                     3
client  -----------------> server1(nginx-websockify) -----------------> server2(nginx-websockify) -----------------> Tcp server
           <----------------                                             <----------------                                             <----------------
                  6                                                                       5                                                                     4

**Comment by tg123** [comment]
为什么要转发两次
第二次时候已经是 websocket 协议了 转发后使用需要 解websocket 两次
