### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by bAndie91** [tg123/websockify-nginx-module#7]
does it support unix domain sockets?

**Comment by tg123** [comment]
upstreams are domain sockets or listen as a domain socket.

**Comment by bAndie91** [comment]
upstream UDS, eg. ```websockify_pass unix:/tmp/vnc.sock;```
In meantime, I checked my config and I discovered websockify does not parse parameter properly, when it is passed as variable:
works:
```websockify_pass unix:/tmp/vnc.sock;```
buggy:
```set $socket unix:/tmp/vnc.sock;
websockify_pass $socket;``` 
log:
```[error] 16553#0: *30 no port in upstream "/tmp/vnc.sock" while sending to client```

**Comment by tg123** [comment]
seems a parsing problem here 

https://github.com/tg123/websockify-nginx-module/blob/master/ngx_http_websockify_module.c#L813

I will try to fix it
