### ISSUE TITLE
Build fails with nginx 1.6.3 and 1.8.1

### ISSUE THREAD

**Issue by Garreat** [tg123/websockify-nginx-module#9]
Hello.
I'm trying to build nginx source with this module included. Tried nginx 1.6.3 and 1.8.1.
For both versions, configure fails with message:
```
adding module in /tmp/nginx/websockify-nginx-module-master/
/tmp/nginx/websockify-nginx-module-master//config: line 7: auto/module: No such file or directory
```
(the double backslash makes no difference)
I'm using Docker image of CentOS 7 with upstream gcc and make.
I can successfully include other modules (ngx_http_auth_pam, nginx-sticky-module-ng) without trouble.

Removing the troublesome line 7 allows successful configuration (ngx 1.8.1), but I'm yet to see if the functionality is there.

**Comment by tg123** [comment]
Fixed lastest commit 
I did not support old config style when support dynamic module (ngx 1.9.11+)

**Comment by Garreat** [comment]
Wow that was quick.
Compiles like a charm now, thanks!
